# Запуск контейнера

version: "3.9"

services:
  bot:
    image: boguk95/horoscope-bot:latest
    container_name: horoscope_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"



