# Запуск контейнера

services:
  bot:
    build: .
    container_name: horoscope_bot_v2
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"